// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF10imn8GoWJkTiNkOXkUo-CJ72xlZ20g',
    appId: '1:90443044459:web:46622cfdecb5fdd341432e',
    messagingSenderId: '90443044459',
    projectId: 'speak-gpt',
    authDomain: 'speak-gpt.firebaseapp.com',
    storageBucket: 'speak-gpt.appspot.com',
    measurementId: 'G-70ZDG8ZKCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClsdluvdGCKU7K3hTQAczkknikC2lgZUA',
    appId: '1:90443044459:android:9669a2282587674341432e',
    messagingSenderId: '90443044459',
    projectId: 'speak-gpt',
    storageBucket: 'speak-gpt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4wsVUPXM9zHenZ68kIjAerzK3YbWlbmQ',
    appId: '1:90443044459:ios:c8f5c5950284959941432e',
    messagingSenderId: '90443044459',
    projectId: 'speak-gpt',
    storageBucket: 'speak-gpt.appspot.com',
    iosClientId: '90443044459-fci18g168ipp7em9fa22jclnndj5p6ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4wsVUPXM9zHenZ68kIjAerzK3YbWlbmQ',
    appId: '1:90443044459:ios:c8f5c5950284959941432e',
    messagingSenderId: '90443044459',
    projectId: 'speak-gpt',
    storageBucket: 'speak-gpt.appspot.com',
    iosClientId: '90443044459-fci18g168ipp7em9fa22jclnndj5p6ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkGpt',
  );
}
